version: '2'

services:
  app:
    image: 'survey-compose-app'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://db:5432/surveydb
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/surveydb
    depends_on:
      - db
  db:
    image: 'postgres:alpine'
    container_name: db
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=surveydb